# Author: Igibek Koishybayev
name: 'Argus Action'
description: 'Static analyzer for GitHub Actions workflow and third-party actions to detect code injection vulnerabilities.'
inputs:
  mode:
    description: 'Argus supports two modes of operation. The "action" mode can be used to analyze the custom actions, the "repo" mode is used to analyze the repository workflows'
    required: true
    default: 'repo'
  workflow:
    description: "Workflow to analyze. By default it will analyze all the workflows under .github/workflows folder. This maybe time consuming."
    required: false
  reference:
    description: "The repository reference (branch, tag, commit) that will be used during scan"
    required: false
    default: ${{ github.sha }}

runs:
  using: "composite"
  steps:
    # setup codeql
    - name: Setting up the CodeQL
      run: |
        cd ${{ github.action_path }}/bin
        wget -q https://github.com/github/codeql-cli-binaries/releases/download/v2.13.3/codeql-linux64.zip
        unzip -qq codeql-linux64.zip
      shell: bash
    
    - run: git clone -q --depth 1 -b codeql-cli/v2.13.3 https://github.com/github/codeql ${{ github.action_path }}/bin/codeql-repo
      shell: bash
    
    # setup python environment
    - name: Setting up the python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        # cache: "pip"
        # cache-dependency-path: ${{ github.action_path}}/requirements.txt

    # install dependencies
    - name: Install pip dependencies
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt -q
      shell: bash

    # run the argus with provided inputs
    - name: Run the argus
      run: python ${{ github.action_path }}/argus.py --mode=${{ inputs.mode }} --url=${{github.repositoryUrl}} --reference=$REFERENCE --output-folder=${{ github.workspace }} --verbose
      shell: bash
      env:
        REFERENCE: ${{ inputs.reference }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Copy the sarif results to workspace
      id: sarif-files
      run: cp -r ${{ github.action_path }}/results ${{ github.workspace }}/sarif-output
      shell: bash
 
    - name: Upload SARIF files
      if: ${{ hashFiles('sarif-output/') != '' }} # https://stackoverflow.com/questions/71336204/github-action-check-if-a-file-already-exists
      uses: github/codeql-action/upload-sarif@v3
      with:
        # Path to SARIF file relative to the root of the repository. We can path sarif-output folder to upload the whole folder
        sarif_file: ${{github.workspace}}/sarif-output
        # Optional category for the results
        # Used to differentiate multiple results for one commit
        category: argus-action
